server:
  port: 9090

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/hungrytech
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  thymeleaf:
    cache: false
logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace